name: amap_all_fluttify
description: An `Amap` Flutter plugin, include `search`, `location`, `map` component.
version: 0.5.0
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_all_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_search_fluttify: 0.3.4+97873c8
  amap_location_fluttify: 0.4.0+82a2243
  amap_map_fluttify: 0.10.2+a1a3fff

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_all_fluttify
    pluginClass: AmapAllFluttifyPlugin