name: amap_all_fluttify
description: An `Amap` Flutter plugin, include `search`, `location`, `map` component.
version: 0.12.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_all_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_search_fluttify: ^0.7.9+481e45c
  amap_location_fluttify: ^0.8.11+481e45c
  amap_map_fluttify: ^0.18.2+c038d50

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_all_fluttify
    pluginClass: AmapAllFluttifyPlugin