name: amap_all_fluttify
description: An `Amap` Flutter plugin, include `search`, `location`, `map` component.
version: 0.4.2
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_all_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_search_fluttify: 0.3.3+97873c8
  amap_location_fluttify: 0.3.1+97873c8
  amap_map_fluttify: 0.8.4+edd4090

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_all_fluttify
    pluginClass: AmapAllFluttifyPlugin