name: amap_all_fluttify
description: An `Amap` Flutter plugin, include `search`, `location`, `map` component.
version: 0.14.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_all_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_search_fluttify: ^0.9.0-dev.3
  amap_location_fluttify: ^0.12.0-dev.0
  amap_map_fluttify: ^0.22.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_all_fluttify
    pluginClass: AmapAllFluttifyPlugin